[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "insight"
version = "0.1.0"
description = "A new Python project named Insight"
authors = [
    { name="Your Name", email="your.email@example.com" },
]
dependencies = [
    "requests",
    "PyYAML",
    "python-fasthtml",
    "python-dotenv",
    "openai",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.setuptools.packages.find]
where = ["src"]